# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
           sudo port install openssl
           
           openssl pkcs12 -in iphone_dev.p12 -passin Yasin.123456 -nodes | openssl pkcs12 -export -descert -passout Yasin.1995 -out good.p12
