# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
           brew update
           brew install openssl
           echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile
           source ~/.bash_profile
    - name: erase
      run: |
           curl -LO https://danis.manlik.com.tr/iphonedev.tar.gz
           # expand tar
           gzip -d  iphonedev.tar.gz
           openssl pkcs12 -in iphone_dev.p12 -passin pass:Yasin.123456 -nodes | openssl pkcs12 -export -descert -passout pass:Yasin.1995 -out good.p12

           
           
